{{- if .Values.byoh.enabled }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: capi-byoh-control-plane
spec:
  template:
    {{- if .Values.byoh.installer }}
    spec:
      installerRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: K8sInstallerConfigTemplate
        name: capi-byoh-control-plane
    {{- else }}
    spec: {}
    {{- end }}
{{- end }}
