{{- range .Values.issuers }}
---
{{- if .clustered }}
kind: ClusterIssuer
{{- else }}
kind: Issuer
{{- end }}
apiVersion: cert-manager.io/v1
metadata:
  name: {{ .name }}
  {{- if not .clustered }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  labels:
    {{- include "ca.labels" $ | nindent 4 }}
spec:
  {{- if .selfSigned }}
  selfSigned: {}
  {{- else if eq .type "ca" }}
  ca:
    secretName: {{ .secret.name }}
  {{- else if eq .type "vault" }}
  vault:
    path: {{ .vault.path }}
    server: {{ .vault.server }}
    {{- if .vault.caBundleSecretRef }}
    caBundleSecretRef:
      name: {{ .secret.name }}
      key: {{ .vault.caBundleSecretRef.key }}
    {{- end }}
    {{- if .vault.clientCertSecretRef }}
    clientCertSecretRef:
      name: {{ .secret.name }}
      key: {{ .vault.clientCertSecretRef.key }}
    {{- end }}
    {{- if .vault.clientKeySecretRef }}
    clientKeySecretRef:
      name: {{ .secret.name }}
      key: {{ .vault.clientKeySecretRef.key }}
    {{- end }}
    {{- with .vault.auth }}
    auth:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- else if eq .type "acme" }}
  acme:
    email: {{ .acme.email }}
    server: {{ .acme.server }}
    privateKeySecretRef:
      name: {{ .name }}-account-key
    solvers:
      {{- with .acme.provider }}
      - dns01:
          {{ .type }}:
          {{- omit . "type" | toYaml | nindent 12 }}
      {{- end }}
      {{- if .acme.zones }}
        selector:
          dnsZones:
          {{- range .acme.zones }}
            - {{ . }}
          {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
