{{- if or .Values.issuers .Values.certificates }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-resource-creator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ca.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-resource-creator
  labels:
    {{- include "ca.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
rules:
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests
      - certificates
      - clusterissuers
      - issuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-resource-creator
  labels:
    {{- include "ca.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
subjects:
  - kind: ServiceAccount
    name: cert-manager-resource-creator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cert-manager-resource-creator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
