{{- range .Values.issuers }}
{{- if and .secret.create (not .selfSigned) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
  namespace: {{ .certManagerNamespace }}
data:
  {{- if eq .type "ca" }}
  tls.crt: {{ .secret.ca.crt | default "" | b64enc  }}
  tls.key: {{ .secret.ca.key | default "" | b64enc  }}
  {{- else if and (eq .type "acme") (eq .acme.provider.type "webhook") }}
  token: {{ .secret.token | default "" | b64enc }}
  {{- else if and (eq .type "acme") (eq .acme.provider.type "rfc2136") }}
  tsig: {{ .secret.tsig | default "" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
