{{- range .Values.issuers }}
{{- if and .secret.create (not .selfSigned) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ca.secretName" . }}
  namespace: {{ .certManagerNamespace }}
  labels:
    {{- include "ca.labels" $ | nindent 4 }}
data:
  {{- if eq .type "ca" }}
  tls.crt: {{ .secret.ca.crt | default "" | b64enc  }}
  tls.key: {{ .secret.ca.key | default "" | b64enc  }}
  {{- else if eq .type "vault" }}
  ca: {{ .secret.ca | default "" | b64enc }}
  client:
    crt: {{ .secret.client.crt | default "" | b64enc }}
    key: {{ .secret.client.key | default "" | b64enc }}
  {{- else if and (eq .type "acme") (.acme.provider.config) (.acme.provider.config.usernameSecretRef) }}
  username: {{ .secret.username | default "" | b64enc }}
  {{- end }}
  {{- if and (eq .type "acme") (.acme.provider.config) (.acme.provider.config.passwordSecretRef) }}
  password: {{ .secret.password | default "" | b64enc }}
  {{- else if and (eq .type "acme") (.acme.provider.config) (.acme.provider.config.secretName) }}
  api-key: {{ .secret.apiKey | default "" | b64enc }}
  {{- else if and (eq .type "acme") (eq .acme.provider.type "rfc2136") }}
  tsig: {{ .secret.tsig | default "" | b64enc }}
  {{- else if and (eq .type "acme") }}
  token: {{ .secret.token | default "" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
