---
apiVersion: v2
name: fleet
type: application
description: A Helm chart that deploys fleet and its dependencies.
version: 7.0.15
dependencies:
  - name: fleet
    repository: https://fleetdm.github.io/fleet/charts
    version: v7.0.15
  - name: ca
    repository: oci://ghcr.io/labsonline/charts
    version: 1.0.8
    condition: ca.enabled
  - name: gateway
    repository: oci://ghcr.io/labsonline/charts
    version: 1.0.4
    condition: gateway.enabled
