{{- if .Values.event.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "knative.fullname" . }}-eventing"
  labels:
    {{- include "knative.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "knative.fullname" . }}
      restartPolicy: OnFailure
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e

              cat > /tmp/eventing.yaml <<'EOF'
              apiVersion: operator.knative.dev/v1beta1
              kind: KnativeEventing
              metadata:
                name: knative-eventing
                labels:
                  {{- include "knative.labels" . | nindent 12 }}
              spec:
                version: {{ .Values.version | quote }}
                defaultBrokerClass: {{ .Values.event.defaultBrokerClass }}
                {{- if .Values.event.config.enabled }}
                config:
                  {{- with .Values.event.config.channel }}
                  default-ch-webhook:
                    {{- . | toYaml | nindent 14 }}
                  {{- end }}
                  {{- with .Values.event.config.broker }}
                  config-br-default-channel:
                    {{- . | toYaml | nindent 14 }}
                  {{- end }}
                {{- end }}
                {{- if .Values.event.sources.enabled }}
                source:
                  ceph:
                    enabled: {{ .Values.event.sources.ceph }}
                  github:
                    enabled: {{ .Values.event.sources.github }}
                  gitlab:
                    enabled: {{ .Values.event.sources.gitlab }}
                  kafka:
                    enabled: {{ .Values.event.sources.kafka }}
                  natss:
                    enabled: {{ .Values.event.sources.natss }}
                  rabbitmq:
                    enabled: {{ .Values.event.sources.rabbitmq }}
                  redis:
                    enabled: {{ .Values.event.sources.redis }}
                {{- end }}
                {{- if .Values.event.backstage.enabled }}
                additionalManifests:
                  - URL: https://github.com/knative-extensions/backstage-plugins/releases/download/knative-{{ .Values.event.backstage.version | default .Values.version }}/eventmesh.yaml
                {{- end }}
                {{- with .Values.event.deployments }}
                deployments:
                  {{- . | toYaml | nindent 12 }}
                {{- end }}
              EOF

              echo "Waiting for KnativeEventing CRD to become available..."
              until kubectl get crd knativeeventings.operator.knative.dev >/dev/null 2>&1; do
                echo "Waiting for knativeeventings.operator.knative.dev CRD..."
                sleep 5
              done

              echo "Applying KnativeEventing configuration..."
              kubectl apply -f /tmp/eventing.yaml || exit 1

              echo "KnativeEventing resource created successfully"
{{- end }}
