{{- if or .Values.server.enabled .Values.event.enabled .Values.resources }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-resource-creator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "knative.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-resource-creator
  labels:
    {{- include "knative.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
rules:
  - apiGroups:
      - operator.knative.dev
    resources:
      - knativeservings
      - knativeeventings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - eventing.knative.dev
    resources:
      - brokers
      - rabbitmqbrokerconfigs
      - triggers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - sources.knative.dev
    resources:
      - containersources
      - kafkasources
      - rabbitmqsources
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - serving.knative.dev
    resources:
      - configurations
      - revisions
      - routes
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-resource-creator
  labels:
    {{- include "knative.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
subjects:
  - kind: ServiceAccount
    name: knative-resource-creator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: knative-resource-creator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
