{{- if and .Values.resources .Values.resources.rabbitmq .Values.resources.rabbitmq.enabled .Values.resources.rabbitmq.clusterRef }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "knative.fullname" . }}-source"
  labels:
    {{- include "knative.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "7"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "knative.fullname" . }}
      restartPolicy: OnFailure
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e

              cat > /tmp/sources.yaml <<'EOF'
              {{- range .Values.resources.rabbitmq.sources }}
              {{- $vhost := $.Values.resources.rabbitmq.clusterRef.vhost }}
              {{- $clusterName := $.Values.resources.rabbitmq.clusterRef.name }}
              {{- $clusterNamespace := $.Values.resources.rabbitmq.clusterRef.namespace | default "default" }}
              ---
              apiVersion: sources.knative.dev/v1alpha1
              kind: RabbitmqSource
              metadata:
                name: {{ .name }}
                labels:
                  {{- include "knative.labels" $ | nindent 12 }}
              spec:
                {{- if $vhost }}
                vhost: {{ $vhost }}
                {{- end }}
                rabbitmqClusterReference:
                  name: {{ $clusterName }}
                  namespace: {{ $clusterNamespace }}
                rabbitmqResourcesConfig:
                  exchangeName: {{ .exchangeName }}
                  queueName: {{ .queueName }}
                {{- with .sinkRef }}
                sink:
                  ref:
                    {{- toYaml . | nindent 14 }}
                {{- end }}
              {{- end }}
              EOF

              echo "Waiting for RabbitmqSource CRD to become available..."
              until kubectl get crd rabbitmqsources.sources.knative.dev >/dev/null 2>&1; do
                echo "Waiting for rabbitmqsources.sources.knative.dev CRD..."
                sleep 5
              done

              echo "Applying RabbitmqSource configurations..."
              kubectl apply -f /tmp/sources.yaml || exit 1

              echo "RabbitmqSource resources created successfully"
{{- end }}
