{{- if and .Values.resources .Values.resources.rabbitmq .Values.resources.rabbitmq.enabled .Values.resources.rabbitmq.clusterRef }}
{{- range .Values.resources.rabbitmq.sources }}
{{- $vhost := $.Values.resources.rabbitmq.clusterRef.vhost }}
{{- $clusterName := $.Values.resources.rabbitmq.clusterRef.name }}
{{- $clusterNamespace := $.Values.resources.rabbitmq.clusterRef.namespace | default "default" }}
---
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: {{ .name }}
  labels:
    {{- include "knative.labels" $ | nindent 4 }}
spec:
  {{- if $vhost }}
  vhost: {{ $vhost }}
  {{- end }}
  rabbitmqClusterReference:
    name: {{ $clusterName }}
    namespace: {{ $clusterNamespace }}
  rabbitmqResourcesConfig:
    exchangeName: {{ .exchangeName }}
    queueName: {{ .queueName }}
  {{- with .sinkRef }}
  sink:
    ref:
      {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
