{{- if .Values.flux.enabled }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcm.labels" . | nindent 4 }}
spec:
  interval: 10m0s
  releaseName: flux
  targetNamespace: {{ .Release.Namespace }}
  timeout: 15m0s
  chart:
    metadata:
      labels:
        k0rdent.mirantis.com/managed: "true"
    spec:
      chart: flux
      version: 2.17.2
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
  # TODO: images
  # postRenderers:
  #   - kustomize:
  #       images:
  #         - name: ""
  #           newName: ""
  #           newTag: ""
  {{- with .Values.flux }}
  values:
    flux:
    {{- omit . "enabled" | toYaml | nindent 6 }}
  {{- end }}
{{- end }}
