{{- if .Values.kcm.gateway }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kcm-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcm.labels" . | nindent 4 }}
    # k0rdent.mirantis.com/managed: "true"
spec:
  interval: 10m0s
  releaseName: kcm-gateway
  targetNamespace: kube-system
  timeout: 15m0s
  {{- if or .Values.flux.enabled .Values.gwapi.enabled .Values.certmanager.enabled .Values.kcm.issuer }}
  dependsOn:
  {{- if .Values.flux.enabled }}
    - name: flux
  {{- end }}
  {{- if .Values.gwapi.enabled }}
    - name: gateway-api
  {{- end }}
  {{- if .Values.certmanager.enabled }}
    - name: cert-manager
  {{- end }}
  {{- if .Values.kcm.issuer }}
    - name: kcm-issuer
  {{- end }}
  {{- end }}
  chart:
    spec:
      chart: gateway
      version: 1.0.3
      # metadata:
      #   labels:
      #     k0rdent.mirantis.com/managed: "true"
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
  install:
    remediation:
      remediateLastFailure: true
      retries: 3
  {{- with .Values.kcm.gateway }}
  values:
    gateways:
    - {{ toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
