{{- if .Values.kcm.repository.enabled }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kcm-templates
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcm.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
spec:
  provider: {{ .provider | default "generic" }}
  interval: {{ .interval | default "10m0s" }}
  type: {{ .type | default "oci" }}
  {{- if eq .Values.kcm.type "enterprise" }}
  url: {{ .Values.kcm.enterprise.templatesRepoURL }}
  {{- else if eq .Values.kcm.type "community" }}
  url: {{ .Values.kcm.community.templatesRepoURL }}
  {{- end }}
  {{- with .secretRef }}
  secretRef:
    name: {{ .name }}
  {{- end }}
{{- end }}
{{- range .Values.repositories }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ .name }}-catalog
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "kcm.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
spec:
  provider: {{ .provider | default "generic" }}
  interval: {{ .interval | default "10m0s" }}
  type: {{ .type | default "oci" }}
  url: {{ .url }}
  {{- with .secretRef }}
  secretRef:
    name: {{ .name }}
  {{- end }}
{{- end }}
