{{- if .Values.kcm.release.enabled }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kcm-enterprise
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcm.labels" . | nindent 4 }}
spec:
  interval: 10m0s
  releaseName: kcm-enterprise
  targetNamespace: {{ .Release.Namespace }}
  timeout: 15m0s
  {{- if or .Values.flux.enabled .Values.certmanager.enabled }}
  dependsOn:
  {{- if .Values.flux.enabled }}
    - name: flux
  {{- end }}
  {{- if .Values.certmanager.enabled }}
    - name: cert-manager
  {{- end }}
  {{- end }}
  chart:
    metadata:
      labels:
        k0rdent.mirantis.com/managed: "true"
    spec:
      chart: {{ include "kcm.chart.name" . }}
      version: {{ include "kcm.chart.version" . }}
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
  # TODO: images
  # postRenderers:
  #   - kustomize:
  #       images:
  #         - name: ""
  #           newName: ""
  #           newTag: ""
  values:
    replicas: {{ .Values.kcm.replicas }}
    admissionWebhook:
      enabled: true
    {{- with .Values.kcm.controller }}
    controller:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if eq .Values.kcm.type "community" }}
      templatesRepoURL: {{ .Values.kcm.community.templatesRepoURL }}
    {{- else if eq .Values.kcm.type "enterprise" }}
      templatesRepoURL: {{ .Values.kcm.enterprise.templatesRepoURL }}
      globalK0sURL: {{ .Values.kcm.enterprise.globalK0sURL }}
      globalRegistry: {{ .Values.kcm.enterprise.globalRegistry }}
    {{- with .Values.kcm.enterprise.k0rdentUI }}
    k0rdent-ui:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    regional:
      cert-manager:
        enabled: false
      cluster-api-operator:
        enabled: true
      velero:
        enabled: true
      telemetry:
        mode: {{ .Values.kcm.regional.telemetry.mode | default "disabled" }}
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    {{- with .Values.kcm.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
