{{- if .Values.management.enabled }}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Management
metadata:
  name: kcm
  labels:
    {{- include "kcm.labels" . | nindent 4 }}
spec:
  release: {{ include "kcm.template.kcm" . }}
  {{- with .Values.management.providers }}
  providers:
    {{- range . }}
    - name: {{ .name }}
    {{- end }}
  {{- end }}
  core:
    capi: {}
    kcm:
      config:
        replicas: {{ .Values.kcm.replicas }}
        admissionWebhook:
          enabled: true
        {{- with .Values.kcm.controller }}
        controller:
          {{- omit . "createTemplates" | toYaml | nindent 10 }}
          createTemplates: false
        {{- end }}
        {{- if eq .Values.kcm.type "community" }}
        templatesRepoURL: {{ .Values.kcm.community.templatesRepoURL }}
        {{- else if eq .Values.kcm.type "enterprise" }}
        templatesRepoURL: {{ .Values.kcm.enterprise.templatesRepoURL }}
        globalK0sURL: {{ .Values.kcm.enterprise.globalK0sURL }}
        globalRegistry: {{ .Values.kcm.enterprise.globalRegistry }}
        {{- with .Values.kcm.enterprise.k0rdentUI }}
        k0rdent-ui:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        regional:
          cert-manager:
            enabled: false
          cluster-api-operator:
            enabled: true
          velero:
            enabled: true
          telemetry:
            mode: {{ .Values.kcm.regional.telemetry.mode | default "disabled" }}
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        {{- with .Values.kcm.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
