{{- if eq (include "kcm.release" .) "true" }}
{{- $providers := list }}
{{- if eq .Values.kcm.type "enterprise" }}
{{- $providers = .Values.kcm.enterprise.release.providers }}
{{- else if eq .Values.kcm.type "community" }}
{{- $providers = .Values.kcm.community.release.providers }}
{{- end }}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Release
metadata:
  name: {{ include "kcm.template.kcm" . }}
  labels:
    {{- include "kcm.labels" . | nindent 4 }}
spec:
  version: {{ include "kcm.chart.version" . }}
  capi:
    template: {{ include "kcm.template.capi" . }}
  kcm:
    template: {{ include "kcm.template.kcm" . }}
  regional:
    template: {{ include "kcm.template.regional" . | default "" }}
  {{- if $providers }}
  providers:
    {{- range $providers }}
    - name: {{ .name }}
      template: {{ .template }}
    {{- end }}
  {{- end }}
{{- end }}
