{{- if .Values.cilium.advert.bgp.enabled }}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAnnouncementPolicy
metadata:
  name: {{ include "cni-resources.fullname" . }}-peer-config
  labels:
    {{- include "cni-resources.labels" . | nindent 4 }}
spec:
  advertisements:
    {{-  if .Values.cilium.advert.bgp.podCIDR }}
    - advertisementType: PodCIDR
      attributes: {{ .Values.cilium.advert.bgp.podCIDR.attributes | toYaml | nindent 10 }}
    {{- end }}
    {{-  if .Values.cilium.advert.bgp.service }}
    - advertisementType: "Service"
      {{- if .Values.cilium.advert.bgp.service.selector }}
      selector: {{ .Values.cilium.advert.bgp.service.selector | toYaml | nindent 12 }}
      {{- end }}
      service:
        addresses: {{ .Values.cilium.advert.bgp.service.addresses | toYaml | nindent 12 }}
    {{- end }}
{{- end }}
