{{- if .Values.cilium.config.peer.enabled }}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: {{ include "cni-resources.fullname" . }}-peer-config
  labels:
    {{- include "cni-resources.labels" . | nindent 4 }}
spec:
  authSecretRef: {{ .Values.cilium.config.peer.authSecretRef }}
  ebgpMultihop: {{ .Values.cilium.config.peer.multiHop }}
  timers:
    holdTimeSeconds: {{ .Values.cilium.config.peer.holdTimeSec }}
    keepAliveTimeSeconds: {{ .Values.cilium.config.peer.keepAliveTimeSec }}
  gracefulRestart:
    enabled: {{ .Values.cilium.config.peer.gracefulRestart }}
    restartTimeSeconds: {{ .Values.cilium.config.peer.restartTimeSec }}
  families: {{- range .Values.cilium.config.peer.addressFamilies }}
    - afi: {{ .afi }}
      safi: {{ .safi }}
      {{- if .advertisements }}
      advertisements:
        {{- toYaml .advertisements | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
