# Add 'repo' label to any root file changes
repo:
  - "*"

# Add 'helm' label to helm chart
helm:
  - deployment/chart/*
  - deployment/chart/**

# Add 'docs' label to files in docs
docs:
  - docs/*
  - docs/**/*

# Add 'scripts' label to files in scripts
scripts:
  - "*"

# Add 'tooling' label to change within tools and .run
tooling:
  - tools/*
  - tools/*/**
