{{- if and .Values.operator.gatewayAPI.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-private
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: netbird-private
  listeners:
  - protocol: gateway.netbird.io/NBRoutingPeer
    name: {{ .Release.Name }}
    port: 1
{{- end }}
