{{- if and .Values.operator.gatewayAPI.enabled }}
---
apiVersion: netbird.io/v1
kind: NBRoutingPeer
metadata:
  name: {{ include "netbird.name" . }}
  namespace: {{ .Release.Namespace }}
spec: {}
{{- end }}
