annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
apiVersion: v2
appVersion: "4.3"
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
description: Omada enables the network administrators to monitor and manage all the
  Omada products in the network with a centralized management platform.
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/omada-controller
icon: https://www.tp-link.com/assets/images/icon/logo-white.svg
keywords:
- omada-controller
kubeVersion: '>=1.16.0-0'
maintainers:
- email: charlie-haley@users.noreply.github.com
  name: charlie-haley
name: omada-controller
sources:
- https://github.com/mbentley/docker-omada-controller
- https://github.com/k8s-at-home/charts/tree/master/charts/omada-controller
version: 4.4.2
