---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy
  namespace: kube-system
spec:
  interval: 10m0s
  releaseName: envoy
  timeout: 15m0s
  chart:
    spec:
      interval: 5m
      chart: gwapi
      version: 1.0.8
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: sre
  install:
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    envoy:
      crds:
        envoyGateway:
          enabled: true
        gatewayAPI:
          enabled: false
      proxies:
        - name: envoy-proxy
          serviceType: NodePort
          patch:
            type: JSONMerge
            value:
              spec:
                ports:
                - name: http
                  nodePort: 80
                  port: 80
                  protocol: TCP
                  targetPort: 10080
                - name: https
                  nodePort: 443
                  port: 443
                  protocol: TCP
                  targetPort: 10443
                # - name: https
                #   nodePort: 8080
                #   port: 8080
                #   protocol: TCP
                #   targetPort: 18080
                # - name: https
                #   nodePort: 8443
                #   port: 8443
                #   protocol: TCP
                #   targetPort: 18443
          logging:
            level:
              default: info
      classes:
        - name: envoy
          parametersRef:
            group: gateway.envoyproxy.io
            kind: EnvoyProxy
            name: envoy-proxy
            namespace: kube-system
      config:
        envoyGateway:
          gateway:
            controllerName: gateway.envoyproxy.io/gatewayclass-controller
          provider:
            type: Kubernetes
          logging:
            level:
              default: info
          extensionApis: {}
