---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: pinniped-2-4-23
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: pinniped
      version: 2.4.23
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
