{{- if .Values.auth.enabled }}
---
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: {{ .Values.auth.name }}
  labels:
    {{- include "pinniped.labels" . | nindent 4 }}
spec:
  issuer: {{ .Values.auth.issuer.url }}
  audience: {{ .Values.auth.audience }}
  {{- if .Values.auth.issuer.ca }}
  tls:
    certificateAuthorityData: {{ .Values.auth.issuer.ca | b64enc }}
  {{- end }}
{{- end }}
