{{- range $i, $v := .Values.rbac }}
{{- $namespace := "pinniped-system" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $v.name }}
  {{- if $v.namespace }}
  {{- $namespace = $v.namespace }}
  {{- else if and .Release .Release.Namespace }}
  {{- $namespace = .Release.Namespace }}
  {{- end }}
  namespace: {{ $namespace }}
  labels:
    {{- include "pinniped.labels" . | nindent 4 }}
{{- with $v.subjects }}
subjects:
  {{- range $j, $subject := . }}
  - kind: {{ $subject.kind }}
    name: {{ $subject.name }}
    apiGroup: {{ $subject.apiGroup | default "rbac.authorization.k8s.io" }}
  {{- end }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $v.role.kind }}
  name: {{ $v.role.name }}
{{- end }}
{{- if or .Values.idp.enabled .Values.auth.enabled .Values.domain.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pinniped.fullname" . }}-crd-waiter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pinniped.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pinniped.fullname" . }}-crd-waiter
  labels:
    {{- include "pinniped.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups:
      - idp.supervisor.pinniped.dev
    resources:
      - oidcidentityproviders
    verbs:
      - create
      - get
      - list
      - patch
      - update
  - apiGroups:
      - authentication.concierge.pinniped.dev
    resources:
      - jwtauthenticators
    verbs:
      - create
      - get
      - list
      - patch
      - update
  - apiGroups:
      - config.supervisor.pinniped.dev
    resources:
      - federationdomains
    verbs:
      - create
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pinniped.fullname" . }}-crd-waiter
  labels:
    {{- include "pinniped.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ include "pinniped.fullname" . }}-crd-waiter
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pinniped.fullname" . }}-crd-waiter
{{- end }}
