{{- if .Values.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  name: pinniped
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.gateway.hostnames }}
  hostnames:
  {{- range . }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  rules:
    - backendRefs:
        - name: pinniped-supervisor
          port: 443
{{- end }}
