# Control plane provider
{{- if .Values.controlPlane }}
{{- $controlPlanes := split ";" .Values.controlPlane }}
{{- $controlPlaneNamespace := "" }}
{{- $controlPlaneName := "" }}
{{- $controlPlaneVersion := "" }}
{{- range $controlPlane := $controlPlanes }}
{{- $controlPlaneArgs := split ":" $controlPlane }}
{{- $controlPlaneArgsLen :=  len $controlPlaneArgs }}
{{-  if eq $controlPlaneArgsLen 3 }}
  {{- $controlPlaneNamespace = $controlPlaneArgs._0 }}
  {{- $controlPlaneName = $controlPlaneArgs._1 }}
  {{- $controlPlaneVersion = $controlPlaneArgs._2 }}
{{-  else if eq $controlPlaneArgsLen 2 }}
  {{- $controlPlaneNamespace = print $controlPlaneArgs._0 "-control-plane-system" }}
  {{- $controlPlaneName = $controlPlaneArgs._0 }}
  {{- $controlPlaneVersion = $controlPlaneArgs._1 }}
{{-  else if eq $controlPlaneArgsLen 1 }}
  {{- $controlPlaneNamespace = print $controlPlaneArgs._0 "-control-plane-system" }}
  {{- $controlPlaneName = $controlPlaneArgs._0 }}
{{- else }}
  {{- fail "controlplane provider argument should have the following format kubeadm:v1.0.0 or mynamespace:kubeadm:v1.0.0" }}
{{-  end }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $controlPlaneNamespace }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: {{ $controlPlaneName }}
  namespace: {{ $controlPlaneNamespace }}
{{- if or $controlPlaneVersion $.Values.configSecret.name }}
spec:
{{- end}}
{{- if $controlPlaneVersion }}
  version: {{ $controlPlaneVersion }}
{{- end }}
{{- if $.Values.manager }}
  manager:
{{- if and (kindIs "map" $.Values.manager.featureGates) (hasKey $.Values.manager.featureGates $controlPlaneName) }}
{{- range $key, $value := $.Values.manager.featureGates }}
  {{- if eq $key $controlPlaneName }}
    featureGates:
    {{- range $k, $v := $value }}
      {{ $k }}: {{ $v }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if $.Values.configSecret }}
{{- if and (kindIs "map" $.Values.configSecret) (hasKey $.Values.configSecret $controlPlaneName) }}
{{- range $key, $value := $.Values.configSecret }}
  {{- if eq $key $controlPlaneName }}
  configSecret:
    {{- range $k, $v := $value }}
    {{- if or (eq $k "name") (eq $k "namespace") }}
    {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
