{{- if and .Values.byoh.enabled .Values.byoh.installer }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: K8sInstallerConfigTemplate
metadata:
  name: capi-byoh-control-plane
spec:
  template:
    spec:
      bundleType: k8s
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: K8sInstallerConfigTemplate
metadata:
  name: capi-capd-machine
spec:
  template:
    spec:
      bundleType: k8s
{{- end }}
