---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: operator-1-0-1
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: operator
      version: 1.0.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
