{{- if .Values.cilium.ipPool.enabled }}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: {{ include "cni-resources.fullname" . }}-ip-pool
  labels:
    {{- include "cni-resources.labels" . | nindent 4 }}
spec:
  allowFirstLastIPs: {{ .Values.cilium.ipPool.allowFirstLastIPs }}
  blocks:
    - cidr: {{ .Values.cilium.ipPool.cidr }}
{{- end }}
