{{- if and .Values.openstack.enabled .Values.k0s.enabled }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: capi-openstack-k0s
spec:
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
      kind: OpenStackClusterTemplate
      name: capi-openstack-cluster
  controlPlane:
    {{- with .Values.machineHealthCheck }}
    machineHealthCheck:
      {{ . | toYaml | nindent 6 }}
    {{- end }}
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: K0sControlPlaneTemplate
      name: capi-k0s-control-plane
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
        kind: OpenStackMachineTemplate
        name: capi-openstack-control-plane
  workers:
    machineDeployments:
      - class: default-worker
        {{- with .Values.machineHealthCheck }}
        machineHealthCheck:
          {{ . | toYaml | nindent 10 }}
        {{- end }}
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: K0sWorkerConfigTemplate
              name: capi-k0s-bootstrap
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
              kind: OpenStackMachineTemplate
              name: capi-openstack-machine
  variables:
    - name: siteName
      schema:
        openAPIV3Schema:
          type: string
          description: SiteName is the name of the site.
          example: dev
    - name: domainName
      schema:
        openAPIV3Schema:
          type: string
          description: DomainName is the domain name of the cluster.
          example: cluster.local
    - name: flavor
      required: true
      schema:
        openAPIV3Schema:
          type: string
          description: The OpenStack flavor to use for the servers.
          example: m1.small
    - name: sshKeyName
      required: true
      schema:
        openAPIV3Schema:
          type: string
          description: The OpenStack SSH key name to use for the servers.
          example: my-key
    - name: apiServerLoadBalancer
      schema:
        openAPIV3Schema:
          type: boolean
          description: The OpenStack LoadBalancer to use for the API server.
          default: true
          example: true
    - name: identityRef
      required: true
      schema:
        openAPIV3Schema:
          type: object
          description: The OpenStack Identity reference.
          properties:
            name:
              type: string
              description: The name of the OpenStack Identity.
              example: my-identity
            cloudName:
              type: string
              description: The name of the OpenStack cloud.
              example: my-cloud
    - name: managedSubnets
      required: true
      schema:
        openAPIV3Schema:
          type: array
          description: The OpenStack managed subnets.
          items:
            type: object
            properties:
              cidr:
                type: string
                description: The CIDR of the OpenStack managed subnet.
                example: 10.6.0.0/24
              dnsNameservers:
                type: array
                items:
                  type: string
                  description: The DNS nameservers for the OpenStack managed subnet.
                  example: 1.1.1.1
  patches:
    - name: sans
      description: Add the cluster name to the SANs of the control plane.
      definitions:
        - selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: K0sControlPlaneTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: add
              path: /spec/template/spec/k0sConfigSpec/k0s/spec/api/sans
              valueFrom:
                template: |
                  - 'kubernetes.{{ `{{ .builtin.cluster.name }}` }}.{{ `{{ .siteName }}` }}.{{ `{{ .domainName }}` }}'
    - name: version
      description: Add the cluster topology version to the K0s version.
      definitions:
        - selector:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: K0sWorkerConfigTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker
          jsonPatches:
            - op: add
              path: /spec/template/spec/version
              valueFrom:
                template: '{{ `{{ .builtin.cluster.topology.version }}` }}+k0s.0'
    - name: clusterConfig
      description: Sets the OpenStack API server load balancer.
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
            kind: OpenStackClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: add
              path: /spec/template/spec/apiServerLoadBalancer/enabled
              valueFrom:
                variable: apiServerLoadBalancer
            - op: add
              path: /spec/template/spec/identityRef
              valueFrom:
                variable: identityRef
            - op: add
              path: /spec/template/spec/managedSubnets
              valueFrom:
                variable: managedSubnets
    - name: controlPlaneConfig
      description: Sets the OpenStack flavor and SSH key name for the control plane servers.
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
            kind: OpenStackMachineTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: add
              path: /spec/template/spec/flavor
              valueFrom:
                variable: flavor
            - op: add
              path: /spec/template/spec/sshKeyName
              valueFrom:
                variable: sshKeyName
            - op: add
              path: /spec/template/spec/image/name
              valueFrom:
                template: |
                  'ubuntu-2204-kube-{{ `{{ .builtin.controlPlane.version }}` }}'
    - name: workerConfig
      description: Sets the OpenStack flavor and SSH key name for the worker servers.
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
            kind: OpenStackMachineTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker
          jsonPatches:
            - op: add
              path: /spec/template/spec/flavor
              valueFrom:
                variable: flavor
            - op: add
              path: /spec/template/spec/sshKeyName
              valueFrom:
                variable: sshKeyName
            - op: add
              path: /spec/template/spec/image/name
              valueFrom:
                template: |
                  'ubuntu-2204-kube-{{ `{{ .builtin.machineDeployment.version }}` }}'
{{- end }}
