{{- if .Values.redis.enabled }}
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ include "msr.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  numberOfInstances: {{ .Values.postgresql.replicas }}
  teamId: msr
  volume:
    size: {{ .Values.postgresql.storage.size }}
    storageClass: {{ .Values.postgresql.storage.class }}
  users:
    msr:  # database owner
    - superuser
    - createdb
  databases:
    registry: msr  # dbname: owner
  postgresql:
    version: {{ .Values.postgresql.version | quote }}
  {{- with .Values.postgresql.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.postgresql.nodeAffinity }}
  nodeAffinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
