{{- if .Values.redis.enabled }}
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: {{ include "msr.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
spec:
  clusterSize: {{ .Values.redis.replicas }}
  kubernetesConfig:
    image: "{{ .Values.redis.image.repo }}:{{ .Values.redis.image.tag }}"
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: {{ include "msr.fullname" . }}-redis-secret
      key: REDIS_PASSWORD
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: {{ .Values.redis.storage.class }}
        resources:
          requests:
            storage: {{ .Values.redis.storage.size }}
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  {{- with .Values.redis.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.redis.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
