{{- if .Values.certmanager.enabled }}
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cert-manager
  labels:
    {{- include "helm-chart-proxy.labels" . | nindent 4 }}
spec:
  namespace: cert-manager
  chartName: cert-manager
  releaseName: cert-manager
  repoURL: {{ .Values.certmanager.repoURL }}
  version: {{ .Values.certmanager.version }}
  clusterSelector:
    {{- toYaml .Values.certmanager.selector | nindent 4 }}
  options:
    timeout: {{ .Values.certmanager.timeout }}
    wait: {{ .Values.certmanager.wait }}
    waitForJobs: {{ .Values.certmanager.waitForJobs }}
  {{- with .Values.certmanager.valuesTemplate }}
  valuesTemplate: |
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
