{{- if .Values.vsphereccm.enabled }}
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cloud-provider-vsphere
  labels:
    {{- include "helm-chart-proxy.labels" . | nindent 4 }}
spec:
  namespace: {{ .Values.vsphereccm.namespace }}
  chartName: vsphere-cpi
  releaseName: cloud-provider-vsphere
  repoURL: {{ .Values.vsphereccm.repoURL }}
  version: {{ .Values.vsphereccm.version }}
  clusterSelector:
    {{- toYaml .Values.vsphereccm.selector | nindent 4 }}
  options:
    timeout: {{ .Values.vsphereccm.timeout }}
    wait: {{ .Values.vsphereccm.wait }}
    waitForJobs: {{ .Values.vsphereccm.waitForJobs }}
  {{- with .Values.vsphereccm.valuesTemplate }}
  valuesTemplate: |
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.vspherecsi.enabled }}
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: csi-vsphere
  labels:
    {{- include "helm-chart-proxy.labels" . | nindent 4 }}
spec:
  namespace: {{ .Values.vspherecsi.namespace }}
  chartName: csi-driver-vsphere
  releaseName: csi-vsphere
  repoURL: {{ .Values.vspherecsi.repoURL }}
  version: {{ .Values.vspherecsi.version }}
  clusterSelector:
    {{- toYaml .Values.vspherecsi.selector | nindent 4 }}
  options:
    timeout: {{ .Values.vspherecsi.timeout }}
    wait: {{ .Values.vspherecsi.wait }}
    waitForJobs: {{ .Values.vspherecsi.waitForJobs }}
  {{- with .Values.vspherecsi.valuesTemplate }}
  valuesTemplate: |
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
