---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: ldap-2025-2-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: ldap
      version: 2025.2.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
