{{- if .Values.collector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring.fullname" . }}-otel-collector
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.collector.replicas }}
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: otel-collector
  template:
    metadata:
      labels:
        {{- include "monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: otel-collector
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/otelcollector/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.collector.securityContext.runAsNonRoot }}
        seccompProfile:
          {{- toYaml .Values.collector.securityContext.seccompProfile | nindent 10 }}
      containers:
        - name: otel-collector
          image: "{{ .Values.collector.image.registry }}/{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}"
          imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.collector.securityContext | nindent 12 }}
          env:
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.collector.clickhouse.secret.name }}
                  key: {{ .Values.collector.clickhouse.secret.key }}
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol-contrib/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "monitoring.fullname" . }}-otel-collector
{{- end }}
