{{- if .Values.collector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-otel-collector
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
{{- end }}
