apiVersion: v2
appVersion: 1.16.0
dependencies:
  - condition: knative-operator.enabled
    name: knative-operator
    repository: file://../knative-operator
    version: ">= 0.2.0"
description: A helm chart to deploy Knative Eventing
name: knative-eventing
type: application
version: 0.3.0
