knative:
  defaultBrokerClass: MTChannelBasedBroker

config:
  channel:
    enabled: false
    default-ch-config: |
      clusterDefault:
        apiVersion: messaging.knative.dev/v1beta1
        kind: InMemoryChannel
        spec:
          delivery:
              backoffDelay: PT0.5S
              backoffPolicy: exponential
              retry: 5
  broker:
    enabled: false
    channel-template-spec: |
      apiVersion: messaging.knative.dev/v1beta1
      kind: InMemoryChannel
      spec:
          delivery:
              backoffDelay: PT0.5S
              backoffPolicy: exponential
              retry: 5

sources:
  ceph:
    enabled: false
  github:
    enabled: false
  gitlab:
    enabled: false
  kafka:
    enabled: false
  natss:
    enabled: false
  rabbitmq:
    enabled: false
  redis:
    enabled: false

#
# suitable for up to 2,500 events/sec per replica
deployments: []
# Broker
#
# - name: mt-broker-ingress
#   resources:
#   - container: ingress
#     requests:
#       cpu: 150m
#       memory: 100Mi
#     limits:
#       cpu: '2'
#       memory: 500Mi
# - name: mt-broker-filter
#   resources:
#   - container: filter
#     requests:
#       cpu: 500m
#       memory: 70Mi
#     limits:
#       cpu: '4'
#       memory: 500Mi
# In-memory channel
#
# - name: imc-dispatcher
#   resources:
#   - container: dispatcher
#     requests:
#       cpu: 200m
#       memory: 250Mi
#     limits:
#       cpu: '4'
#       memory: 1500Mi

backstage:
  enabled: false
  version: v1.16.0

knative-operator:
  enabled: false
