{{- if .Values.vsphere.enabled }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: capi-vsphere-control-plane
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: {{ .Values.vsphere.datacenter }}
      datastore: {{ .Values.vsphere.datastore }}
      diskGiB: {{ .Values.vsphere.diskGiB }}
      folder: {{ .Values.vsphere.folder }}
      memoryMiB: {{ .Values.vsphere.memoryMiB }}
      numCPUs: {{ .Values.vsphere.numCPUs }}
      os: Linux
      powerOffMode: trySoft
      resourcePool: {{ .Values.vsphere.resourcePool | quote }}
      storagePolicyName: {{ .Values.vsphere.storagePolicyName }}
      template: {{ .Values.vsphere.template }}
      network:
        devices:
          - dhcp4: true
            networkName: {{ .Values.vsphere.networkName }}
{{- end }}
