{{- if and (not .Release.IsInstalled) (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "helmrepositories.source.toolkit.fluxcd.io") }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kcm-templates
  namespace: {{ .Release.Namespace }}
  labels:
    k0rdent.mirantis.com/managed: 'true'
spec:
  interval: 10m0s
  provider: generic
  type: oci
  url: oci://ghcr.io/k0rdent/kcm/charts
{{- end }}
