{{- if .Capabilities.APIVersions.Has "source.toolkit.fluxcd.io/v1" -}}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kcm-templates
  namespace: {{ .Release.Namespace }}
  labels:
    k0rdent.mirantis.com/managed: 'true'
spec:
  interval: 10m0s
  provider: generic
  type: oci
  url: {{ .Values.controller.templatesRepoURL }}
{{- end }}
