---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: monitoring-3-7-1
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: monitoring
      version: 3.7.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
