---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: monitoring-1-0-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: monitoring
      version: 1.0.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
