nameOverride: ""
fullnameOverride: ""

sshPubKey: ""

kubeadm:
  enabled: true

k0s:
  enabled: false
  nodeLocalLoadBalancing: false
  postStartCommands: []
  preInstalledK0s: false
  preStartCommands: []
  tunneling:
    enabled: "false"
    serverAddress: ""
  args: []
  # - --no-taints
  # - --enable-worker

docker:
  enabled: false

openstack:
  enabled: false

metal3:
  enabled: false
  image:
    checksum: ""
    url: ""

byoh:
  enabled: false
  installer: true

vsphere:
  enabled: false
  datacenter: ""
  datastore: ""
  diskGiB: 25
  folder: ""
  memoryMiB: 8192
  networkName: ""
  numCPUs: 2
  resourcePool: ""
  storagePolicyName: ""
  template: ""

featureGates:
  - name: UserNamespacesSupport
    enabled: true

machineHealthCheck:
  maxUnhealthy: 30%
  nodeStartupTimeout: 15m
  unhealthyConditions:
    - type: Ready
      status: Unknown
      timeout: 300s
    - type: Ready
      status: "False"
      timeout: 300s
