---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: cni-1-0-3
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cni
      version: 1.0.3
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
