---
apiVersion: v2
name: aistor
type: application
description: A Helm chart that deploys MinIO AIStor and its dependencies.
version: 1.0.2
dependencies:
  - alias: aistorop
    name: aistor-operator
    repository: https://helm.min.io
    version: 5.11.0
    condition: aistorop.enabled
  - alias: aistor
    name: aistor-objectstore
    repository: https://helm.min.io
    version: 1.0.16
    condition: aistor.enabled
  - name: ca
    repository: oci://ghcr.io/labsonline/charts
    version: 1.0.7
    condition: ca.enabled
  - name: gateway
    repository: oci://ghcr.io/labsonline/charts
    version: 1.0.4
    condition: gateway.enabled
