---
apiVersion: v2
type: application
name: ca
description: A Helm chart that deploys cert-manager and its dependencies.
version: 1.0.0
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.19.2
    condition: cert-manager.enabled
  - name: trust-manager
    repository: https://charts.jetstack.io
    version: 0.20.3
    condition: trust-manager.enabled
