---
apiVersion: v2
type: application
name: ca
description: A Helm chart that deploys cert-manager and its dependencies.
version: 1.0.3
dependencies:
  - alias: certmanager
    name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.19.2
    condition: certmanager.enabled
  - alias: trustmanager
    name: trust-manager
    repository: https://charts.jetstack.io
    version: 0.20.3
    condition: trustmanager.enabled
