---
apiVersion: v2
name: vault
type: application
description: A Helm chart that deploys Vault and it's dependencies.
version: 0.23.5
dependencies:
  - alias: vault
    name: openbao
    repository: oci://ghcr.io/openbao/charts
    version: 0.23.5
  - name: data
    repository: oci://ghcr.io/labsonline/charts
    version: 1.0.0
  - name: ca
    repository: oci://ghcr.io/labsonline/charts
    version: 1.0.4
