---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m0s
  releaseName: cert-manager
  timeout: 15m0s
  dependsOn:
    - name: flux
      namespace: sre
    # - name: traefik-gateway-api
    #   namespace: kube-system
  chart:
    spec:
      interval: 5m
      chart: ca
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: sre
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
  # TODO: images
  # postRenderers:
  #   - kustomize:
  #       images:
  #         - name: ""
  #           newName: ""
  #           newTag: ""
  values:
    issuers:
      - name: ca-issuer
        clustered: true
        selfSigned: true
        secret:
          create: false
    certmanager:
      enabled: true
      # config:
      #   enableGatewayAPI: true
