# FIXME: Update values as needed
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maas
  namespace: ucp
spec:
  interval: 10m0s
  releaseName: maas
  timeout: 15m0s
  dependsOn:
    - name: flux
      namespace: sre
    - name: operator
      namespace: operators
    - name: envoy
      namespace: kube-system
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      interval: 5m
      chart: maas
      version: 3.6.2
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: sre
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
  # TODO: images
  # postRenderers:
  #   - kustomize:
  #       images:
  #         - name: ""
  #           newName: ""
  #           newTag: ""
  values:
    # TODO: maas values
    maas: {}
    data:
      postgres:
        enabled: false
        postgresVersion: 17
        instances:
          - name: maasdb
            replicas: 1
            dataVolumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
        proxy:
          pgBouncer:
            replicas: 1
    gateway:
      routes:
        - name: maas
          kind: HTTPRoute
          hostnames:
            - maas.k8s.orb.local
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /
              backendRefs:
                - name: maas-region
                  port: 5240
          gateways:
            - name: http-gateway
              namespace: kube-system
