# FIXME: Update values as needed
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: ucp
spec:
  interval: 10m0s
  releaseName: netbox
  timeout: 15m0s
  dependsOn:
    - name: flux
      namespace: sre
    - name: operator
      namespace: operators
    - name: envoy
      namespace: kube-system
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      interval: 5m
      chart: netbox
      version: 7.4.1
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: sre
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
  # TODO: images
  # postRenderers:
  #   - kustomize:
  #       images:
  #         - name: ""
  #           newName: ""
  #           newTag: ""
  values:
    netbox:
      superuser:
        existingSecret: netbox-credential
      admins:
        - ['admin', 'admin@orb.local']
      banner:
        top: ""
        bottom: ""
        login: ""
      cors:
        originRegexWhitelist:
          - '^(https?://)?(\w+\.)?k8s\.orb\.local$'
          - '^(https?://)?(\w+\.)?orb\.local$'
      csrf:
        trustedOrigins:
          - https://netbox.k8s.orb.local
      extraConfig:
        - secret:
            secretName: netbox-oidc-credential
        - values:
            SOCIAL_AUTH_VERIFY_SSL: False
            SOCIAL_AUTH_OIDC_OIDC_ENDPOINT: https://vault.k8s.orb.local/v1/identity/oidc/provider/default
            SOCIAL_AUTH_OIDC_OIDC_SCOPE:
              - openid
              - groups
              - email
              - username
      httpRoute:
        enabled: true
        parentRefs:
          - name: http-gateway
            namespace: kube-system
        hostnames:
          - netbox.k8s.orb.local
      postgresql:
        enabled: false
      externalDatabase:
        host: netbox-postgres-primary.ucp.svc.cluster.local
        port: 5432
        database: netbox-postgres
        username: netbox-postgres
        existingSecretName: netbox-postgres-pguser-netbox-postgres
        existingSecretKey: password
        options:
          sslmode: require
          sslrootcert: /etc/ssl/certs/pg-ca.crt
      valkey:
        enabled: false
      tasksDatabase:
        database: 0
        host: netboxcache-master.ucp.svc.cluster.local
        port: 6379
        sentinelService: netboxcache-master.ucp.svc.cluster.local
      cachingDatabase:
        database: 1
        host: netboxcache-master.ucp.svc.cluster.local
        port: 6379
        sentinelService: netboxcache-master.ucp.svc.cluster.local
      # FIXME: superuser & staff groups have no effect
      remoteAuth:
        enabled: true
        backends:
          - social_core.backends.open_id_connect.OpenIdConnectAuth
        superuserGroups:
          - admins
        staffGroups:
          - users
      extraVolumes:
        - name: pg-ca-cert
          secret:
            secretName: netbox-postgres-cluster-cert
            items:
              - key: ca.crt
                path: ca.crt
      extraVolumeMounts:
        - name: pg-ca-cert
          mountPath: /etc/ssl/certs/pg-ca.crt
          subPath: ca.crt
          readOnly: true
      # DEBUG: Disable livenessProbe
      livenessProbe:
        enabled: false
    data:
      postgres:
        enabled: true
        postgresVersion: 17
        instances:
          - name: netboxdb
            replicas: 1
            dataVolumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
        proxy:
          pgBouncer:
            replicas: 1
      redisreplication:
        enabled: true
        redisReplication:
          name: netboxcache
          clusterSize: 1
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
      redissentinel:
        enabled: true
        redisSentinel:
          name: netboxsentinel
          clusterSize: 3
        redisSentinelConfig:
          redisReplicationName: netboxcache
