# FIXME: Update values as needed
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: ucp
spec:
  interval: 10m0s
  releaseName: netbox
  timeout: 15m0s
  dependsOn:
    - name: flux
      namespace: sre
    - name: operator
      namespace: operators
    - name: envoy
      namespace: kube-system
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      interval: 5m
      chart: netbox
      version: 7.4.1
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: sre
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
  # TODO: images
  # postRenderers:
  #   - kustomize:
  #       images:
  #         - name: ""
  #           newName: ""
  #           newTag: ""
  values:
    # TODO: netbox values
    netbox: {}
    data:
      postgres:
        enabled: false
        postgresVersion: 17
        instances:
          - name: netboxdb
            replicas: 1
            dataVolumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
        proxy:
          pgBouncer:
            replicas: 1
