# FIXME: Update values as needed
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
  namespace: operators
spec:
  interval: 10m0s
  releaseName: operator
  timeout: 15m0s
  dependsOn:
    - name: flux
      namespace: sre
  chart:
    spec:
      interval: 5m
      chart: operator
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: sre
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
  # TODO: images
  # postRenderers:
  #   - kustomize:
  #       images:
  #         - name: ""
  #           newName: ""
  #           newTag: ""
  values:
    postgres:
      enabled: true
      watchAllNamespaces: true
      disableTelemetry: true
    redis:
      enabled: true
