# FIXME: Update values as needed
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: ucp
spec:
  interval: 10m0s
  releaseName: vault
  timeout: 15m0s
  dependsOn:
    - name: flux
      namespace: sre
    # - name: operator
    #   namespace: operators
    # - name: traefik-gateway-api
    #   namespace: kube-system
    # - name: cert-manager
    #   namespace: cert-manager
  chart:
    spec:
      interval: 5m
      chart: vault
      version: 0.23.5
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: sre
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
  # TODO: images
  # postRenderers:
  #   - kustomize:
  #       images:
  #         - name: ""
  #           newName: ""
  #           newTag: ""
  values:
    vault:
      injector:
        metrics:
          enabled: false
      server:
        # resources:
        #   requests:
        #     memory: 256Mi
        #     cpu: 250m
        #   limits:
        #     memory: 256Mi
        #     cpu: 250m
        # gateway:
        #   tlsRoute:
        #     enabled: true
        #     hosts:
        #       - vault.local
        #     parentRefs:
        #       - name: traefik
        #         namespace: kube-system
        # fixme: init & unseal
        # postStart:
        #   - /bin/sh
        #   - -c
        #   - bao operator init
        # note:
        # openssl rand -out ./unseal-20251231-1.key 32
        # openssl rand -out ./unseal-20260122-1.key 32
        # kubectl create secret generic -n ucp unseal-20251231-1 --from-file ./unseal-20251231-1.key
        # kubectl create secret generic -n ucp unseal-20260122-1 --from-file ./unseal-20260122-1.key
        volumes:
          - name: unseal-20251231-1
            secret:
              secretName: unseal-20251231-1
          - name: unseal-20260122-1
            secret:
              secretName: unseal-20260122-1
        volumeMounts:
          - name: unseal-20251231-1
            mountPath: /openbao/secrets/unseal-20251231-1.key
            subPath: unseal-20251231-1.key
            readOnly: true
          - name: unseal-20260122-1
            mountPath: /openbao/secrets/unseal-20260122-1.key
            subPath: unseal-20260122-1.key
            readOnly: true
        standalone:
          config: |
            ui = true

            # api_addr = "https://vault.k8s.orb.local"

            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              #telemetry {
              #  unauthenticated_metrics_access = "true"
              #}
            }

            storage "file" {
              path = "/openbao/data"
            }

            # storage "postgresql" {
            #   connection_url = "postgres://vault:vault@postgres:5432/vault?sslmode=disable"
            # }

            seal "static" {
              current_key_id = "20260122-1"
              current_key = "file:///openbao/secrets/unseal-20260122-1.key"
              previous_key_id = "20251231-1"
              previous_key = "file:///openbao/secrets/unseal-20251231-1.key"
            }

            # seal "pkcs11" {
            #   lib         = "/usr/local/lib/libpkcs11-proxy.so.0.1"
            #   token_label = "VaultToken"
            #   key_label   = "vault-root-key-rsa"
            #   mechanism   = "CKM_RSA_PKCS_OAEP"
            # }

            # Example configuration for enabling Prometheus metrics in your config.
            #telemetry {
            #  prometheus_retention_time = "30s"
            #  disable_hostname = true
            #}
