---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: data-1-0-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: data
      version: 1.0.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
