cilium:
  pool:
    enabled: true
    allowFirstLastIPs: No
    cidr: 172.16.0.0/24
  advert:
    l2:
      enabled: false
      externalIPs: true
      loadBalancerIPs: true
    bgp:
      enabled: true
      service:
        # selector:
        #   matchExpressions:
        #     - { key: bgp, operator: In, values: [blue] }
        addresses:
          - ExternalIP
          - LoadBalancerIP
      # podCIDR:
      #   attributes:
      #     localPreference: 99
      #     communities:
      #       standard: ["65000:99"]
  config:
    cluster:
      enabled: true
      # nodeSelector:
      #   matchLabels:
      #     rack: rack0
      instances:
        - name: cilium
          localASN: 65000
          peers:
            - name: peer-1
              peerASN: 65000
              peerAddress: fd00:10:0:0::1
              peerConfigRef:
                name: cni-resources-peer-config
    peer:
      enabled: true
      authSecretRef: bgp
      gracefulRestart: true
      holdTimeSec: 9
      keepAliveTimeSec: 3
      multiHop: 4
      restartTimeSec: 15
      addressFamilies:
        - afi: ipv4
          safi: unicast
          advertisements:
            matchLabels:
              advertise: bgp
