{{- if .Values.manifests.configmap_ingress }}
{{ $bind_address_cidr := .Values.network.maas_ingress.addr | splitList "/" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-ingress-services-tcp
data:
{{- if .Values.conf.maas.proxy.proxy_enabled }}
  {{ tuple "maas_region" "public" "region_proxy" . | include "helm-toolkit.endpoints.endpoint_port_lookup" | quote }}: "{{- .Release.Namespace -}}/{{- tuple "maas_region" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" -}}:region-proxy"
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-ingress-services-udp
data:
  '53': "{{- .Release.Namespace -}}/{{- tuple "maas_region" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" -}}:region-dns"
  "514": "{{- .Release.Namespace -}}/{{- tuple "maas_syslog" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" -}}:syslog"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-ingress-config
data:
  enable-underscores-in-headers: "true"
  bind-address: {{ index $bind_address_cidr 0 | quote }}
  disable-ipv6: "true"
{{- end }}
