{{- if and .Values.manifests.ingress_region .Values.network.region_api.ingress.public }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maas-region-api
  metadata:
    annotations:
{{ toYaml .Values.network.region_api.ingress.annotations | indent 8 }}
spec:
  ingressClassName: {{ .Values.network.region_api.ingress.classes.cluster | quote }}
{{- if .Values.conf.maas.tls.enabled }}
  tls:
    - secretName: maas-region-api-tls
      hosts:
        - {{ tuple "maas_region" "public" . | include "helm-toolkit.endpoints.hostname_fqdn_endpoint_lookup" }}
{{ end }}
  rules:
    - host: {{ tuple "maas_region" "public" . | include "helm-toolkit.endpoints.hostname_fqdn_endpoint_lookup" }}
      http:
        paths:
{{- if .Values.conf.maas.ingress_disable_gui }}
          - path: /MAAS/api
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ tuple "maas_region" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
                port:
                  name: region-api
          - path: /MAAS/images-stream
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ tuple "maas_region" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
                port:
                  name: region-api
          - path: /MAAS/metadata
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ tuple "maas_region" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
                port:
                  name: region-api
          - path: /MAAS/rpc
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ tuple "maas_region" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
                port:
                  name: region-api
{{- else }}
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ tuple "maas_region" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
                port:
                  name: region-api
{{- end }}
...
{{ end }}
