{{- $envAll := . }}
{{- range $key1, $userClass := tuple "admin" }}
{{- $secretName := index $envAll.Values.secrets.maas_users $userClass }}
{{- $auth := index $envAll.Values.endpoints.maas_region.auth $userClass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  USERNAME: {{ $auth.username | b64enc }}
  PASSWORD: {{ $auth.password | b64enc }}
  EMAIL: {{ $auth.email | b64enc }}
{{ end }}
