{{- $envAll := . }}
{{- range $key1, $userClass := tuple "admin" "user" }}
{{- $secretName := index $envAll.Values.secrets.maas_db $userClass }}
{{- $auth := index $envAll.Values.endpoints.maas_db.auth $userClass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  DATABASE_HOST: |-
{{ tuple "maas_db" "internal" $envAll | include "helm-toolkit.endpoints.hostname_fqdn_endpoint_lookup" | b64enc | indent 4 }}
  DATABASE_USERNAME: |-
{{ $auth.username | b64enc | indent 4 }}
  DATABASE_PASSWORD: |-
{{ $auth.password | b64enc | indent 4 }}
  DATABASE_NAME: |-
{{ $auth.database | default "" | b64enc | indent 4 }}
  DATABASE_PORT: {{ tuple "maas_db" "internal" "postgresql" $envAll | include "helm-toolkit.endpoints.endpoint_port_lookup" | b64enc }}
{{ end }}
