{{- if and .Values.conf.maas.tls.enabled .Values.conf.maas.tls.create (eq .Values.cert_manager.enabled false) }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.certificate }}
type: kubernetes/tls
data:
  ca.crt: {{ .Values.conf.maas.tls.ca | b64enc }}
  tls.crt: {{ .Values.conf.maas.tls.cert | b64enc }}
  tls.key: {{ .Values.conf.maas.tls.key | b64enc }}
{{ end }}
