{{- $envAll := . }}
{{- $secretName := index $envAll.Values.secrets.maas_region "name" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  REGION_SECRET: |-
{{ $envAll.Values.secrets.maas_region.value | b64enc | indent 4 }}
