---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  labels:
    {{- include "knative-eventing.labels" . | nindent 4 }}
spec:
  version: {{ .Values.knative.version | default .Chart.AppVersion | quote }}
  defaultBrokerClass: {{ .Values.knative.defaultBrokerClass }}
  config:
    {{- if .Values.config.channel.enabled }}
    {{- with .Values.config.channel }}
    default-ch-webhook:
      {{ . | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- if .Values.config.broker.enabled }}
    {{- with .Values.config.broker }}
    config-br-default-channel:
      {{ . | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
  source:
    ceph:
      enabled: {{ .Values.sources.ceph.enabled }}
    github:
      enabled: {{ .Values.sources.github.enabled }}
    gitlab:
      enabled: {{ .Values.sources.gitlab.enabled }}
    kafka:
      enabled: {{ .Values.sources.kafka.enabled }}
    natss:
      enabled: {{ .Values.sources.natss.enabled }}
    rabbitmq:
      enabled: {{ .Values.sources.rabbitmq.enabled }}
    redis:
      enabled: {{ .Values.sources.redis.enabled }}
    additionalManifests:
      {{- if .Values.backstage.enabled }}
      - URL: https://github.com/knative-extensions/backstage-plugins/releases/{{ .Values.backstage.version }}/download/eventmesh.yaml
      {{- end }}
  {{- with .Values.deployments }}
  deployments:
    {{ . | toYaml | nindent 4 }}
  {{- end }}
