---
apiVersion: v2
name: csi
type: application
description: A Helm chart that deploys various CSI drivers and their dependencies.
version: 1.0.2
dependencies:
  - name: openebs
    repository: https://openebs.github.io/openebs
    version: 4.4.0
    condition: openebs.enabled
  - alias: rook
    name: rook-ceph
    repository: https://charts.rook.io/release
    version: v1.18.8
    condition: rook.enabled
  - alias: ceph
    name: rook-ceph-cluster
    repository: https://charts.rook.io/release
    version: v1.18.8
    condition: ceph.enabled
  - alias: ebs
    name: aws-ebs-csi-driver
    repository: file://../../upstream/aws-ebs-csi-driver/charts/aws-ebs-csi-driver
    version: 2.54.1
    condition: ebs.enabled
  - alias: cinder
    name: openstack-cinder-csi
    repository: https://kubernetes.github.io/cloud-provider-openstack
    version: 2.34.1
    condition: cinder.enabled
  - alias: vsphere
    name: vsphere-csi-driver
    repository: https://charts.mirantis.com
    version: 0.0.3
    condition: vsphere.enabled
