{{- if and .Values.cilium.enabled .Values.cilium.l2.enabled }}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announce-policy
spec:
  externalIPs: {{ .Values.cilium.l2.externalIPs }}
  loadBalancerIPs: {{ .Values.cilium.l2.loadBalancerIPs }}
{{- end }}
