{{- if and .Values.cilium.enabled .Values.cilium.pool.enabled }}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-ip-pool
spec:
  allowFirstLastIPs: {{ .Values.cilium.pool.allowFirstLastIPs | quote }}
  blocks:
    - cidr: {{ .Values.cilium.pool.cidr }}
{{- end }}
