{{- if .Values.k0s.enabled }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0sControlPlaneTemplate
metadata:
  name: capi-k0s-control-plane
spec:
  template:
    spec:
      k0sConfigSpec:
        args:
        {{- with .Values.k0s.args }}
          {{ toYaml . | nindent 10 }}
        {{- end }}
        files:
          - path: /home/ubuntu/.ssh/authorized_keys
            content: {{ .Values.sshPubKey }}
        postStartCommands:
        {{-  with .Values.k0s.postStartCommands }}
          {{ toYaml . | nindent 12 }}
        {{- end }}
        preInstalledK0s: {{ .Values.k0s.preInstalledK0s }}
        preStartCommands:
        {{-  with .Values.k0s.preStartCommands }}
          {{ toYaml . | nindent 12 }}
        {{- end }}
        tunneling:
          enabled: {{ .Values.k0s.tunneling.enabled | default "proxy" }}
          mode: {{ .Values.k0s.tunneling.mode }}
          serverAddress: {{ .Values.k0s.tunneling.serverAddress }}
        k0s:
          apiVersion: k0s.k0sproject.io/v1beta1
          kind: ClusterConfig
          metadata:
            name: k0s
          spec:
            api:
              k0sApiPort: {{ .Values.k0s.apiPort | default 9443 }}
              extraArgs:
                anonymous-auth: {{ .Values.k0s.anonymous | default "true" }} # anonymous-auth=true is needed for k0s to allow unauthorized health-checks on /healthz
            konnectivity:
              adminPort: {{ .Values.k0s.konnectivity | default 8133 }}
              agentPort: {{ .Values.k0s.konnectivity | default 8132 }}
            network:
              provider: {{ .Values.k0s.network | default "custom" }}
            nodeLocalLoadBalancing:
              enabled: {{ .Values.k0s.nodeLocalLoadBalancing }}
              type: EnvoyProxy
              envoyProxy:
                apiServerBindPort: {{ .Values.k0s.envoyAPIPort | default 7443 }}
                konnectivityServerBindPort: {{ .Values.k0s.envoyKnnectivityPort | default 7132 }}
            featureGates:
            {{- with .Values.featureGates }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
            telemetry:
                enabled: false
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: capi-k0s-bootstrap
spec:
  template:
    spec:
      files:
        - path: /home/ubuntu/.ssh/authorized_keys
          content: {{ .Values.sshPubKey }}
      postStartCommands:
        {{-  with .Values.k0s.postStartCommands }}
          {{ toYaml . | nindent 12 }}
        {{- end }}
      preInstalledK0s: {{ .Values.k0s.preInstalledK0s }}
      preStartCommands:
        {{-  with .Values.k0s.preStartCommands }}
          {{ toYaml . | nindent 12 }}
        {{- end }}
{{- end }}
