{{- if .Values.kubeadm.enabled }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: capi-kubeadm-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        users:
          - name: administrator
            sudo: ALL=(ALL) NOPASSWD:ALL
            sshAuthorizedKeys:
              - {{ .Values.sshPubKey }}
        files:
          - path: /root/.ssh/authorized_keys
            content: {{ .Values.sshPubKey }}
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
        clusterConfiguration:
          apiServer:
            certSANs:
              - 0.0.0.0
              - 127.0.0.1
              - host.docker.internal
              - localhost
            extraArgs:
              cloud-provider: external
          controllerManager:
            extraArgs:
              cloud-provider: external
              enable-hostpath-provisioner: "true"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: capi-kubeadm-bootstrap
spec:
  template:
    spec:
      kubeadmConfigSpec:
        users:
          - name: administrator
            sudo: ALL=(ALL) NOPASSWD:ALL
            sshAuthorizedKeys:
              - {{ .Values.sshPubKey }}
        files:
          - path: /root/.ssh/authorized_keys
            content: {{ .Values.sshPubKey }}
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
            cloud-provider: external
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
{{- end }}
