{{- if and .Values.peer.enabled .Values.peer.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.name" . }}-setup-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.labels" $ | nindent 4 }}
type: Opaque
string:
  NB_SETUP_KEY: {{ .Values.peer.secret.key | b64enc }}
{{- end }}
