---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: vault-0-23-5
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: vault
      version: 0.23.5
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
