apiVersion: v2
appVersion: 1.16.0
dependencies:
  - condition: knative-operator.enabled
    name: knative-operator
    repository: file://../knative-operator
    version: ">= 0.2.0"
  - condition: cert-manager.enabled
    name: cert-manager
    repository: https://charts.jetstack.io
    version: ">= v1.14.4"
  - condition: ca-issuer.enabled
    name: ca-issuer
    repository: file://../../cert-manager/ca-issuer
    version: ">= 0.2.0"
description: A helm chart to deploy Knative Serving
name: knative-serving
type: application
version: 0.3.0
