knative:
  domain: svc.local
  replicas: 1
  security:
    enabled: false
    guard: false
  network:
    gatewayAPI:
      external: {}
      internal: {}
    kourier:
      service:
        type: LoadBalancer
  ingress:
    # type: gateway-api
    type: kourier

ca-issuer:
  enabled: false
  conf:
    ca:
      issuer:
        name: ""
  manifests:
    issuer: false
    selfsigned: true

cert-manager:
  enabled: false

knative-operator:
  enabled: false
