{{- range .Values.gateways }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .name }}
  {{- range .listeners }}
  {{- if .tls }}
  {{- range .tls.certificateRefs }}
  {{- if .issuer }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .issuer }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
spec:
  gatewayClassName: {{ .className }}
  listeners:
  {{- range .listeners }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      {{- with .allowedRoutes }}
      allowedRoutes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .tls }}
      tls:
        mode: {{ .tls.mode }}
        {{- range .tls.certificateRefs }}
        certificateRefs:
          - name: {{ .name }}
        {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
