{{- range .Values.grants }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ .name }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  {{- with .to }}
  to:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .from }}
  from:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
