{{- range .Values.policies }}
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: {{ .name }}
  labels:
    {{- include "gateway.labels" $ | nindent 4 }}
spec:
  validation:
    hostname: {{ .validation.hostname }}
    {{- if .validation.wellKnownCACertificates }}
    wellKnownCACertificates: {{ .validation.wellKnownCACertificates }}
    {{- end }}
    {{- with .validation.caCertificateRefs }}
    caCertificateRefs:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .targetRefs }}
  targetRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
