{{- range .Values.routes }}
---
{{- if eq .kind "TLSRoute" }}
apiVersion: gateway.networking.k8s.io/v1alpha2
{{- else }}
apiVersion: gateway.networking.k8s.io/v1
{{- end }}
kind: {{ .kind }}
metadata:
  name: {{ .name }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- range .hostnames }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ join "," . }}
  {{- end }}
spec:
  {{- range .hostnames }}
  hostnames:
    - {{ . }}
  {{- end }}
  {{- range .rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- range .gateways }}
  parentRefs:
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
  {{- end }}
{{- end }}
