---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitea-act-runner.fullname" . }}-token
  labels:
  {{- include "gitea-act-runner.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.token | b64enc | quote }}
