---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway
  namespace: kube-system
spec:
  interval: 10m0s
  releaseName: gateway
  timeout: 15m0s
  dependsOn:
    - name: flux
      namespace: sre
    - name: envoy
      namespace: kube-system
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      interval: 5m
      chart: gateway
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: sre
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    gateways:
      - name: http-gateway
        className: envoy
        # addresses:
        #   - type: IPAddress
        #     value: 10.200.201.2
        listeners:
          - name: http
            port: 80
            protocol: HTTP
            allowedRoutes:
              namespaces:
                from: All
              kinds:
                - kind: HTTPRoute
          - name: https
            port: 443
            protocol: HTTPS
            hostname: "*.k8s.orb.local"
            allowedRoutes:
              namespaces:
                from: All
              kinds:
                - kind: HTTPRoute
            tls:
              mode: Terminate
              certificateRefs:
                - name: http-gw-cert
                  issuer: ca-issuer
      # - name: grpc-gateway
      #   className: envoy
      #   # addresses:
      #   #   - type: IPAddress
      #   #     value: 10.200.201.3
      #   listeners:
      #     - name: http
      #       port: 80
      #       protocol: HTTP
      #       allowedRoutes:
      #         namespaces:
      #           from: All
      #         kinds:
      #           - kind: GRPCRoute
      #     - name: grpc
      #       port: 443
      #       protocol: HTTPS
      #       hostname: "*.k8s.orb.local"
      #       allowedRoutes:
      #         namespaces:
      #           from: All
      #         kinds:
      #           - kind: GRPCRoute
      #       tls:
      #         mode: Terminate
      #         certificateRefs:
      #           - name: grpc-gw-cert
      #             issuer: ca-issuer
      # - name: tcp-gateway
      #   className: envoy
      #   # addresses:
      #   #   - type: IPAddress
      #   #     value: 10.200.201.4
      #   listeners:
      #     - name: tcp
      #       port: 80
      #       protocol: TCP
      #       allowedRoutes:
      #         namespaces:
      #           from: All
      #         kinds:
      #           - kind: TCPRoute
      # - name: tls-gateway
      #   className: envoy
      #   # addresses:
      #   #   - type: IPAddress
      #   #     value: 10.200.201.4
      #   listeners:
      #     - name: tls
      #       port: 443
      #       protocol: TLS
      #       hostname: "*.k8s.orb.local"
      #       allowedRoutes:
      #         namespaces:
      #           from: All
      #         kinds:
      #           - kind: TLSRoute
      #       tls:
      #         mode: Passthrough
      # - name: udp-gateway
      #   className: envoy
      #   # addresses:
      #   #   - type: IPAddress
      #   #     value: 10.200.201.5
      #   listeners:
      #     - name: udp
      #       port: 80
      #       protocol: UDP
      #       allowedRoutes:
      #         namespaces:
      #           from: All
      #         kinds:
      #           - kind: UDPRoute
