---
apiVersion: v2
name: maas
type: application
description: A Helm chart that deploys MaaS and it's dependencies.
version: 3.6.2
dependencies:
  - name: helm-toolkit
    repository: file://../../library/helm-toolkit
    version: 2025.2.0
  - name: data
    repository: oci://ghcr.io/labsonline/charts
    version: 1.0.0
  - name: gateway
    repository: oci://ghcr.io/labsonline/charts
    version: 1.0.3
