---
apiVersion: v2
type: application
name: headscale
description: A Helm chart that deploys Headscale and its dependencies.
version: 0.1.0
dependencies:
  - alias: operator
    name: headscale-operator
    repository: oci://ghcr.io/infradohq/headscale-operator/charts
    version: 0.4.0
    condition: operator.enabled
  - name: ca
    repository: oci://ghcr.io/labsonline/charts
    version: 1.0.4
    condition: ca.enabled
  - name: gateway
    repository: oci://ghcr.io/labsonline/charts
    version: 1.0.3
    condition: gateway.enabled
