{{- if and .Values.adminJob.enabled .Values.adminJob.objectStore.policy.enabled .Values.adminJob.objectStore.policy.policies }}
---
apiVersion: sts.min.io/v1beta1
kind: PolicyBinding
metadata:
  name: {{ .Values.adminJob.name }}-policy-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aistor.labels" $ | nindent 4 }}
spec:
  application:
    serviceaccount: {{ .Values.adminJob.serviceAccountName.name }}
    namespace: {{ .Values.adminJob.objectStore.namespace | default .Release.Namespace }}
  {{- with .Values.adminJob.objectStore.policy.policies }}
  policies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
