{{- if and .Values.adminJob.enabled .Values.adminJob.secret.create .Values.adminJob.secret.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminJob.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aistor.labels" $ | nindent 4 }}
data:
  {{- if .Values.adminJob.secret.user }}
  USER: {{ .Values.adminJob.secret.user | b64enc }}
  {{- end }}
  PASSWORD: {{ .Values.adminJob.secret.password | b64enc }}
{{- end }}
