---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: netbox-7-4-1
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: netbox
      version: 7.4.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
