apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "knative-resource.fullname" . }}-event-display
  labels:
  {{- include "knative-resource.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - image: "{{ .Values.service.image.repository }}:{{ .Values.service.image.tag }}"
