{{- if .Values.resources.rabbitmq.enabled }}
{{- range .Values.resources.rabbitmq.brokers }}
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: {{ .name }}
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: RabbitmqBrokerConfig
    name: {{ .config.name }}
  {{- with .deadLetterSink }}
  delivery:
    deadLetterSink:
      ref:
        {{- toYaml .ref | nindent 8 }}
  {{- end }}
{{- end }}
{{- end }}
