{{- if and .Values.proxy.enabled .Values.proxy.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.name" . }}-proxy-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.labels" $ | nindent 4 }}
type: Opaque
string:
  NB_PROXY_TOKEN: {{ .Values.proxy.secret.token | b64enc }}
{{- end }}
