nameOverride: ""
fullnameOverride: ""

cilium:
  enabled: true
  repoURL: https://helm.cilium.io/
  version: 1.16.2
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      cilium: enabled
  valuesTemplate: {}

openebs:
  enabled: false
  repoURL: https://openebs.github.io/charts/
  version: 3.10.0
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      openebs: enabled
  valuesTemplate: {}

certmanager:
  enabled: false
  repoURL: https://charts.jetstack.io/
  version: v1.15.3
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      certmanager: enabled
  valuesTemplate: {}

nfscsi:
  enabled: false
  repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/
  version: v4.9.0
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      nfs: enabled
  valuesTemplate: {}

smbcsi:
  enabled: false
  repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/
  version: v1.16.0
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      smb: enabled
  valuesTemplate: {}

openstackccm:
  enabled: false
  namespace: openstack
  repoURL: https://kubernetes.github.io/cloud-provider-openstack/
  version: 2.31.1
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      openstack: enabled
  valuesTemplate: {}

cindercsi:
  enabled: false
  namespace: openstack
  repoURL: https://kubernetes.github.io/cloud-provider-openstack/
  version: 2.31.1
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      cinder: enabled
  valuesTemplate: {}

manilacsi:
  enabled: false
  namespace: openstack
  repoURL: https://kubernetes.github.io/cloud-provider-openstack/
  version: 2.31.1
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      manila: enabled
  valuesTemplate: {}

vsphereccm:
  enabled: false
  namespace: vsphere
  repoURL: https://kubernetes.github.io/cloud-provider-vsphere/
  version: 1.31.0
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      vsphere: enabled
  valuesTemplate: {}

vspherecsi:
  enabled: false
  repoURL: oci://ghcr.io/sanselme/
  version: 0.1.0
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      vsphere: enabled
  valuesTemplate: {}

flux:
  enabled: false
  namespace: cicd
  repoURL: https://charts.bitnami.com/bitnami/
  version: 2.3.20
  timeout: 5m
  wait: true
  waitForJobs: true
  selector:
    matchLabels:
      flux: enabled
  valuesTemplate: {}
