{{- if .Values.configAsCode.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "gitea-act-runner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitea-act-runner.name" . }}
    helm.sh/chart: {{ include "gitea-act-runner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |
    {{- toYaml .Values.configAsCode.config | nindent 4 }}
{{- end }}
