{{- if .Values.admission.enabled -}}
{{- $cn1 := printf "%s-admission.%s.svc" (include "rockoon.fullname" .) (.Release.Namespace) }}
{{- $cn2 := printf "%s-admission.%s.svc.%s" (include "rockoon.fullname" .) (.Release.Namespace) (.Values.admission.cluster_domain_suffix) }}
{{- $cabundle := genCA $cn1 3650 }}
{{- $client := genSignedCert $cn1  nil (list $cn1 $cn2) 1095 $cabundle }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "rockoon.fullname" . }}-admission
webhooks:
  - name: {{ include "rockoon.fullname" . }}-admission.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: {{ include "rockoon.fullname" . }}-admission
        namespace: {{ .Release.Namespace }}
        path: "/validate"
{{- if empty .Values.admission.tls }}
      caBundle: {{ $cabundle.Cert | b64enc }}
{{- else }}
      caBundle: {{ .Values.admission.tls.ca | b64enc }}
{{- end }}
    rules:
      - operations: [ "CREATE", "UPDATE", "DELETE" ]
        apiGroups: ["lcm.mirantis.com"]
        apiVersions: ["v1alpha1"]
        resources: ["openstackdeployments"]
        scope: "Namespaced"
      - operations: [ "UPDATE" ]
        apiGroups: ["lcm.mirantis.com"]
        apiVersions: ["v1alpha1"]
        resources: ["openstackdeployments/status"]
        scope: "Namespaced"
    sideEffects: None
    admissionReviewVersions: ["v1"]
    timeoutSeconds: 30
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rockoon.fullname" . }}-admission-tls
  namespace: {{ .Release.Namespace }}
data:
{{- if empty .Values.admission.tls }}
  oac.crt: {{ $client.Cert  | b64enc }}
  oac.key: {{ $client.Key  | b64enc }}
  oac.bundle: {{ $cabundle.Cert | b64enc }}
{{- else }}
  oac.crt: {{ .Values.admission.tls.crt | b64enc }}
  oac.key: {{ .Values.admission.tls.key | b64enc }}
  oac.bundle: {{ .Values.admission.tls.ca | b64enc }}
{{- end }}
type: Opaque

{{- end }}

