---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-operator.fullname" . }}-serving-operator-aggregated-stable
  labels:
    {{- include "knative-operator.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
    # This (along with escalate below) allows the Operator to pick up any
    # roles that are provided to the admin of the cluster by knative serving
    # automatically.
    - matchExpressions:
        - {key: app.kubernetes.io/name, operator: In, values: ["knative-serving"]}
rules: [] # Rules are automatically filled in by the controller manager.
