---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  labels:
    {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  version: {{ .Values.knative.version | default .Chart.AppVersion | quote }}
  high-availability:
    replicas: {{ .Values.knative.replicas }}
  {{- if .Values.knative.security }}
  security:
    securityGuard:
      enabled: {{ .Values.knative.security.guard }}
  {{- end }}
  ingress:
    {{- if eq .Values.knative.ingress.type "kourier" }}
    kourier:
      enabled: true
      service-type: {{ .Values.knative.network.kourier.service.type }}
    {{- end }}
    {{- if eq .Values.knative.ingress.type "gateway-api" }}
    istio:
      enabled: false
    {{- end }}
  config:
    domain:
      "{{ .Values.knative.domain }}": ""
    {{- if index .Values "ca-issuer" "enabled" }}
    certmanager:
      issuerRef: |
        kind: ClusterIssuer
        name: {{ index .Values "ca-issuer" "conf" "ca" "issuer" "name" | default "self-signed-ca-issuer" }}
      clusterLocalIssuerRef: |
        kind: ClusterIssuer
        name: {{ index .Values "ca-issuer" "conf" "ca" "issuer" "name" | default "self-signed-ca-issuer" }}
      systemInternalIssuerRef: |
        kind: Issuer
        name: {{ index .Values "ca-issuer" "conf" "ca" "issuer" "name" | default "self-signed-ca-issuer" }}
    {{- end }}
    {{- if eq .Values.knative.ingress.type "gateway-api" }}
    gateway:
      external-gateways: |
        - class: cilium
          gateway: {{ .Values.knative.network.gatewayAPI.external.name | default "kube-system/default" }}
          service: {{ .Values.knative.network.gatewayAPI.external.service | default "kube-system/cilium-gateway-default" }}
          supported-features:
            - HTTPRouteRequestTimeout
      local-gateways: |
        - class: cilium
          gateway: {{ .Values.knative.network.gatewayAPI.internal.name | default "kube-system/knative" }}
          service: {{ .Values.knative.network.gatewayAPI.internal.service | default "kube-system/cilium-gateway-knative" }}
          supported-features:
            - HTTPRouteRequestTimeout
    {{- end }}
    network:
      http-protocol: Redirected
      {{- if eq .Values.knative.ingress.type "kourier" }}
      ingress-class: kourier.ingress.networking.knative.dev
      {{- end }}
      {{- if eq .Values.knative.ingress.type "gateway-api" }}
      ingress-class: gateway-api.ingress.networking.knative.dev
      {{- end }}
      {{- if index .Values "ca-issuer" "enabled" }}
      auto-tls: Enabled
      namespace-wildcard-cert-selector: '{"matchExpressions": [{"key":"networking.knative.dev/disableWildcardCert", "operator": "NotIn", "values":["true"]}]}'
      {{- end }}
    deployment:
      registriesSkippingTagResolving: kind.local,ko.local,dev.local,knative.registry.svc.cluster.local
  additionalManifests:
    {{- if .Values.knative.network.gatewayAPI.install | default false }}
    - URL: https://raw.githubusercontent.com/knative-extensions/net-gateway-api/refs/tags/{{ .Values.knative.network.gatewayAPI.version | default "v0.43.0" }}/config/200-clusterrole.yaml
    - URL: https://raw.githubusercontent.com/knative-extensions/net-gateway-api/refs/tags/{{ .Values.knative.network.gatewayAPI.version | default "v0.43.0" }}/config/300-controller.yaml
    - URL: https://raw.githubusercontent.com/knative-extensions/net-gateway-api/refs/tags/{{ .Values.knative.network.gatewayAPI.version | default "v0.43.0" }}/config/400-webhook-deployment.yaml
    - URL: https://raw.githubusercontent.com/knative-extensions/net-gateway-api/refs/tags/{{ .Values.knative.network.gatewayAPI.version | default "v0.43.0" }}/config/400-webhook-secret.yaml
    - URL: https://raw.githubusercontent.com/knative-extensions/net-gateway-api/refs/tags/{{ .Values.knative.network.gatewayAPI.version | default "v0.43.0" }}/config/400-webhook-service.yaml
    - URL: https://raw.githubusercontent.com/knative-extensions/net-gateway-api/refs/tags/{{ .Values.knative.network.gatewayAPI.version | default "v0.43.0" }}/config/500-validating-webhook.yaml
    - URL: https://raw.githubusercontent.com/knative-extensions/net-gateway-api/refs/tags/{{ .Values.knative.network.gatewayAPI.version | default "v0.43.0" }}/config/config-gateway.yaml
    {{- end }}
