name: Build Pipeline

on:
  push:
    paths:
      - deployment/chart/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: read-all

jobs:
  container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ github.ref == 'refs/heads/main' }}
      matrix:
        repo:
          - name: sanselmechart # fixme: switch to anselmescharts
            url: oci://registry-1.docker.io
            # todo: generate
            charts:
              # note: networking
              - path: deployment/chart/cni/cilium
              - path: deployment/chart/cni/cni-resource
              - path: deployment/charts/osh/openstack-helm-infra/openvswitch
              - path: deployment/charts/osh/openstack-helm-infra/ovn
              - path: deployment/charts/osh/openstack-helm-infra/powerdns
              # note: storage
              - path: deployment/charts/csi/openebs
              - path: deployment/charts/osh/openstack-helm-infra/ceph-adapter-rook
              # note: certs
              - path: deployment/chart/cert-manager/ca-clusterissuer
              - path: deployment/chart/cert-manager/ca-issuer
              - path: deployment/chart/cert-manager/cert-manager
              - path: deployment/chart/cert-manager/cert-manager-webhook-pdns
              - path: deployment/chart/cert-manager/trust-manager
              - path: deployment/charts/osh/openstack-helm-infra/cert-rotation
              # note: observability
              - path: deployment/chart/lgtm/k8s-monitoring
              - path: deployment/chart/lgtm/lgtm-distributed
              - path: deployment/chart/osh/openstack-helm-infra/kubernetes-node-problem-detector
              - path: deployment/charts/osh/openstack-helm-infra/prometheus-blackbox-exporter
              - path: deployment/charts/osh/openstack-helm-infra/prometheus-openstack-exporter
              - path: deployment/charts/osh/openstack-helm-infra/prometheus-process-exporter
              # note: knative
              - path: deployment/chart/knative/knative-eventing
              - path: deployment/chart/knative/knative-operator
              - path: deployment/chart/knative/knative-serving
              # note: cluster-api
              - path: deployment/chart/capi/capi-cluster-class
              - path: deployment/chart/capi/capi-operator
              - path: deployment/chart/capi/capi-provider
              - path: deployment/chart/capi/helm-chart-proxy
              # note: data
              - path: deployment/chart/osh/openstack-helm-infra/mariadb
              - path: deployment/chart/osh/openstack-helm-infra/memcached
              - path: deployment/chart/osh/openstack-helm-infra/mongodb
              - path: deployment/chart/osh/openstack-helm-infra/postgresql
              - path: deployment/chart/osh/openstack-helm-infra/rabbitmq
              - path: deployment/chart/osh/openstack-helm-infra/redis
              # note: openstack
              - path: deployment/charts/osh/openstack-helm/barbican
              - path: deployment/charts/osh/openstack-helm/cinder
              - path: deployment/charts/osh/openstack-helm/designate
              - path: deployment/charts/osh/openstack-helm/glance
              - path: deployment/charts/osh/openstack-helm/heat
              - path: deployment/charts/osh/openstack-helm/horizon
              - path: deployment/charts/osh/openstack-helm/keystone
              - path: deployment/charts/osh/openstack-helm/neutron
              - path: deployment/charts/osh/openstack-helm/nova
              - path: deployment/charts/osh/openstack-helm/octavia
              - path: deployment/charts/osh/openstack-helm/placement
              # note: misc
              - path: deployment/chart/gitea-runner
              - path: deployment/chart/osh/openstack-helm-infra/daemonjob-controller
              - path: deployment/chart/osh/openstack-helm-infra/kubernetes-keystone-webhook
              - path: deployment/chart/osh/openstack-helm-infra/ldap
              - path: deployment/chart/osh/openstack-helm-infra/libvirt
              - path: deployment/chart/osh/openstack-helm-infra/lockdown
              - path: deployment/chart/osh/openstack-helm-infra/metacontroller
              - path: deployment/chart/osh/openstack-helm-infra/namespace-config
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7  https://github.com/actions/checkout/commit/692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Download helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0 https://github.com/Azure/setup-helm/commit/fe7b79cd5ee1e45176fcad797de68ecaf3ca4814
        with:
          version: v3.16.3 # default is latest (stable)


      # fixme: lint
      # - name: Lint charts
      #   run: |
      #     set -x
      #     helm lint ${{ matrix.repo.charts.path }}

      # fixme: template
      # - name: Test charts
      #   run: |
      #     set -x
      #     helm template ${{ matrix.repo.charts.path }}

      # fixme: build
      # - name: Package charts
      #   run: |
      #     set -x
      #     helm package ${{ matrix.repo.charts.path }}

      # fixme: upload
      # - name: Push charts
      #   if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      #   run: |
      #     set -x
      #     helm push ${{ matrix.repo.charts }}.tgz oci://${{ matrix.repo.url }}/${{ matrix.repo.name || github.repository_owner }}
