name: Build Pipeline

on:
  push:
    paths:
      - build/img/**
      - build/scripts/init-devos.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: read-all

jobs:
  # todo: separate build and push
  container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ github.ref == 'refs/heads/main' }}
      # matrix:
      #   repo: []
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7  https://github.com/actions/checkout/commit/692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Download helm
        uses: ./scripts/install-helm.sh

      # - name: Package charts
      #   run: |
      #     helm package charts/{{ matrix.helm.charts }} -d /tmp/
      #     ls -lh /tmp/{{ matrix.helm.charts }}*.tgz

      # - name: Push charts
      #   if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      #   run: |
      #     set -x
      #     echo helm push /tmp/{{ matrix.repo.charts }}*.tgz oci://{{ matrix.repo.url }}/{{ matrix.repo.name || github.repository_owner }}
