{{- if .Values.smbcsi.enabled }}
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: csi-smb
  labels:
    {{- include "helm-chart-proxy.labels" . | nindent 4 }}
spec:
  namespace: kube-system
  chartName: csi-driver-smb
  releaseName: csi-smb
  repoURL: {{ .Values.smbcsi.repoURL }}
  version: {{ .Values.smbcsi.version }}
  clusterSelector:
    {{- toYaml .Values.smbcsi.selector | nindent 4 }}
  options:
    timeout: {{ .Values.smbcsi.timeout }}
    wait: {{ .Values.smbcsi.wait }}
    waitForJobs: {{ .Values.smbcsi.waitForJobs }}
  {{- with .Values.smbcsi.valuesTemplate }}
  valuesTemplate: |
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
